### ISSUE TITLE
Add bagua-net support to bagua-core

### ISSUE THREAD

**Issue by NOBLES5E** [BaguaSys/bagua-net#6]
We can do this in a similar way as we add nccl to bagua-core: https://github.com/BaguaSys/bagua-core/blob/master/setup.py and https://github.com/BaguaSys/bagua-core/blob/master/python/bagua_core/_environment.py

We can control whether to enable `bagua-net` with the environment variable `ENABLE_BAGUA_NET`.

**Comment by shjwudp** [comment]
https://github.com/BaguaSys/bagua-core/pull/89
